# Nombre interno del proyecto dbt.
name: "analytics_platform"
# Versión lógica del proyecto.
version: "1.0.0"
# Versión del formato de configuración.
config-version: 2
# Nombre del perfil de conexión.
profile: "analytics_platform"
# Carpeta donde dbt busca modelos SQL.
model-paths: ["models"]
# Carpeta donde dbt busca macros.
macro-paths: ["macros"]
# Carpeta donde dbt busca tests.
test-paths: ["tests"]
# Carpetas que dbt puede limpiar con dbt clean.
clean-targets:
- "target"
- "dbt_packages"
- "logs"
# Variables reutilizables.
# var("landing_clientes_path") leerá la ruta del CSV.
# var("bronze_clientes_glob") leerá la ruta de los Parquet bronze.
vars:
landing_clientes_path: "../data/landing/clientes/sample_clientes.csv"
bronze_clientes_glob: "../data/bronze/clientes/*/*.parquet"
# Configuración por defecto de modelos.
models:
analytics_platform:
+materialized: view
var() en dbt sirve para leer variables definidas en dbt_project.yml.
Ejemplo:
{{ var("landing_clientes_path") }}
dbt reemplaza eso por:
../data/landing/clientes/sample_clientes.csv